// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbqkyzbaanjrqmveggkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicWt5emJhYW5qcnFtdmVnZ2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjczMzAsImV4cCI6MjA1OTEwMzMzMH0.949ASkgJIJOkRMqyXoiyYZNLTp6hYl39DNPoIFLLNuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);